language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: fad25f31c83dd17c5b74f5aa18c932f031989d65
  keep_history: true
  on:
    branch: master