site_name: Turbo-v10's Documentation
site_url: https://turbov10.github.io/

repo_url: https://github.com/turbov10/turbov10.github.io/
repo_name: GitHub
edit_uri: blob/main/docs/
#remote_name: origin
#remote_branch: gh-pages

nav:
  - Home: 'index.md'
  - 'Kubernetes':
      - 'Kubernetes': 'my-kubernetes/kubernetes.md'
      - 'Kubernetes 容器运行时安装': 'my-kubernetes/k8s_installation_cr.md'
      - 'Kubernetes 集群搭建': 'my-kubernetes/k8s_installation.md'
      - 'Kubernetes 集群常用工具': 'my-kubernetes/k8s_installation_tools.md'
      - 'Kubernetes 基础课 (2022-11-24)': 'my-kubernetes/k8s-lesson-20221124.md'
  - 'Cloud Native':
      - 'Cloud Native Fundamentals': 'my-cloudnative/cloud-native-fundamentals.md'
      - 'containerd': 'my-cloudnative/containerd.md'
  - 'CI/CD':
#      - 'my-cicd/github-actions.md'
      - 'GitHub Actions': 'my-cicd/github-actions.md'
      - 'Harness': 'my-cicd/harness.md'
  - 'Doc Tools':
      - 'MkDocs': 'my-docs/mkdocs.md'

markdown_extensions:
  - toc:
      baselevel: 1
      permalink: '#'

theme:
  name: readthedocs
  locale: zh_CN
  navigation_depth: 1
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - sh


docs_dir: docs
extra_css:
  - css/extra.css

# Plugins
plugins:
  - search
  - mermaid2
#  - redirects:
#      redirect_maps:
#        'getting_started/access.md': 'engineer-onboarding/access.md'
#        'getting_started/agile-practices.md': 'engineer-onboarding/agile-practices.md'
#        'getting_started/create-cluster.md': 'engineer-onboarding/create-cluster.md'
#        'getting_started/demos.md': 'engineer-onboarding/demos.md'
#        'getting_started/faq-troubleshooting.md': 'engineer-onboarding/faq-troubleshooting.md'
#        'getting_started/getting-started.md': 'engineer-onboarding/getting-started.md'
#        'getting_started/offboarding.md': 'engineer-onboarding/offboarding.md'
#        'getting_started/useful-tooling.md': 'engineer-onboarding/useful-tooling.md'
#        'getting_started/vscode.md': 'engineer-onboarding/vscode.md'
#        'getting_started/why.md': 'engineer-onboarding/why.md'
#        'documentation/applications/Media.md': 'how-to/media-howtos.md'

