apiVersion: v1
kind: Pod
metadata:
  name: dapitest
  labels:
    zone: us-east-coast
    cluster: test-cluster1
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels

