apiVersion: v1
kind: Pod
metadata:
  name: temp-volume-pod
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /cache-volume
      name: cache-volume
    - mountPath: /test-hostpath
      name: test-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  - name: test-volume
    hostPath:
      path: /etc # 宿主上目录位置
      type: Directory # 可选