apiVersion: v1
kind: Pod
metadata:
  name: testres
spec:
  containers:
  - name: sleep
    image: curlimages/curl
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    resources: 
      requests: 
        memory: "64M" 
        cpu: "200m"
      limits: 
        memory: "128M" 
        cpu: "500m"

