#probe
apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: gcr.io/google_containers/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: X-Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
######
# http.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
#     duration := time.Now().Sub(started)
#     if duration.Seconds() > 10 {
#         w.WriteHeader(500)
#         w.Write([]byte(fmt.Sprintf("error: %v", duration.Seconds())))
#     } else {
#         w.WriteHeader(200)
#         w.Write([]byte("ok"))
#     }
# })
######
---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-socket
  labels:
    app: liveness-socket
spec:
  containers:
  - name: goproxy
    image: k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
