#yaml 明文模式
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  key: test
  value: test
---

# 投射到pod
---
apiVersion: v1
kind: Pod
metadata:
  name: testpv
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: mysec
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: mysec
    projected:
      sources:
      - secret:
          name: mysec
      - secret:
          name: secret-basic-auth